title: Fire2a Documentation
description: Fire2a research group documentation for published tools
theme: just-the-docs

url: https://fdobad.github.io/docs

aux_links:
  Template Repository: https://github.com/fdobad/docs
